/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StudentBuilderRouteImport } from './routes/student.builder'
import { Route as StudentEditRouteImport } from './routes/student.edit'
import { Route as StudentScheduleRouteImport } from './routes/student.schedule'
import { Route as StudentStatsRouteImport } from './routes/student.stats'
import { Route as StudentSummaryRouteImport } from './routes/student.summary'
import { Route as TrainerIndexRouteImport } from './routes/trainer.index'
import { Route as TrainerBuilderRouteImport } from './routes/trainer.builder'
import { Route as StudentWorkoutIdRouteImport } from './routes/student.workout.$id'
import { Route as TrainerStudentIdRouteImport } from './routes/trainer.student.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/student/',
  path: '/student/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentBuilderRoute = StudentBuilderRouteImport.update({
  id: '/student/builder',
  path: '/student/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentEditRoute = StudentEditRouteImport.update({
  id: '/student/edit',
  path: '/student/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentScheduleRoute = StudentScheduleRouteImport.update({
  id: '/student/schedule',
  path: '/student/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentStatsRoute = StudentStatsRouteImport.update({
  id: '/student/stats',
  path: '/student/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentSummaryRoute = StudentSummaryRouteImport.update({
  id: '/student/summary',
  path: '/student/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerIndexRoute = TrainerIndexRouteImport.update({
  id: '/trainer/',
  path: '/trainer/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerBuilderRoute = TrainerBuilderRouteImport.update({
  id: '/trainer/builder',
  path: '/trainer/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentWorkoutIdRoute = StudentWorkoutIdRouteImport.update({
  id: '/student/workout/$id',
  path: '/student/workout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerStudentIdRoute = TrainerStudentIdRouteImport.update({
  id: '/trainer/student/$id',
  path: '/trainer/student/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/student/builder': typeof StudentBuilderRoute
  '/student/edit': typeof StudentEditRoute
  '/student/schedule': typeof StudentScheduleRoute
  '/student/stats': typeof StudentStatsRoute
  '/student/summary': typeof StudentSummaryRoute
  '/trainer/builder': typeof TrainerBuilderRoute
  '/student/': typeof StudentIndexRoute
  '/trainer/': typeof TrainerIndexRoute
  '/student/workout/$id': typeof StudentWorkoutIdRoute
  '/trainer/student/$id': typeof TrainerStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/student/builder': typeof StudentBuilderRoute
  '/student/edit': typeof StudentEditRoute
  '/student/schedule': typeof StudentScheduleRoute
  '/student/stats': typeof StudentStatsRoute
  '/student/summary': typeof StudentSummaryRoute
  '/trainer/builder': typeof TrainerBuilderRoute
  '/student': typeof StudentIndexRoute
  '/trainer': typeof TrainerIndexRoute
  '/student/workout/$id': typeof StudentWorkoutIdRoute
  '/trainer/student/$id': typeof TrainerStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/student/builder': typeof StudentBuilderRoute
  '/student/edit': typeof StudentEditRoute
  '/student/schedule': typeof StudentScheduleRoute
  '/student/stats': typeof StudentStatsRoute
  '/student/summary': typeof StudentSummaryRoute
  '/trainer/builder': typeof TrainerBuilderRoute
  '/student/': typeof StudentIndexRoute
  '/trainer/': typeof TrainerIndexRoute
  '/student/workout/$id': typeof StudentWorkoutIdRoute
  '/trainer/student/$id': typeof TrainerStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/student/builder'
    | '/student/edit'
    | '/student/schedule'
    | '/student/stats'
    | '/student/summary'
    | '/trainer/builder'
    | '/student/'
    | '/trainer/'
    | '/student/workout/$id'
    | '/trainer/student/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/student/builder'
    | '/student/edit'
    | '/student/schedule'
    | '/student/stats'
    | '/student/summary'
    | '/trainer/builder'
    | '/student'
    | '/trainer'
    | '/student/workout/$id'
    | '/trainer/student/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/student/builder'
    | '/student/edit'
    | '/student/schedule'
    | '/student/stats'
    | '/student/summary'
    | '/trainer/builder'
    | '/student/'
    | '/trainer/'
    | '/student/workout/$id'
    | '/trainer/student/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  StudentBuilderRoute: typeof StudentBuilderRoute
  StudentEditRoute: typeof StudentEditRoute
  StudentScheduleRoute: typeof StudentScheduleRoute
  StudentStatsRoute: typeof StudentStatsRoute
  StudentSummaryRoute: typeof StudentSummaryRoute
  TrainerBuilderRoute: typeof TrainerBuilderRoute
  StudentIndexRoute: typeof StudentIndexRoute
  TrainerIndexRoute: typeof TrainerIndexRoute
  StudentWorkoutIdRoute: typeof StudentWorkoutIdRoute
  TrainerStudentIdRoute: typeof TrainerStudentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/student'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/builder': {
      id: '/student/builder'
      path: '/student/builder'
      fullPath: '/student/builder'
      preLoaderRoute: typeof StudentBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/edit': {
      id: '/student/edit'
      path: '/student/edit'
      fullPath: '/student/edit'
      preLoaderRoute: typeof StudentEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/schedule': {
      id: '/student/schedule'
      path: '/student/schedule'
      fullPath: '/student/schedule'
      preLoaderRoute: typeof StudentScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/stats': {
      id: '/student/stats'
      path: '/student/stats'
      fullPath: '/student/stats'
      preLoaderRoute: typeof StudentStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/summary': {
      id: '/student/summary'
      path: '/student/summary'
      fullPath: '/student/summary'
      preLoaderRoute: typeof StudentSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/': {
      id: '/trainer/'
      path: '/trainer'
      fullPath: '/trainer/'
      preLoaderRoute: typeof TrainerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/builder': {
      id: '/trainer/builder'
      path: '/trainer/builder'
      fullPath: '/trainer/builder'
      preLoaderRoute: typeof TrainerBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/workout/$id': {
      id: '/student/workout/$id'
      path: '/student/workout/$id'
      fullPath: '/student/workout/$id'
      preLoaderRoute: typeof StudentWorkoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/student/$id': {
      id: '/trainer/student/$id'
      path: '/trainer/student/$id'
      fullPath: '/trainer/student/$id'
      preLoaderRoute: typeof TrainerStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  StudentBuilderRoute: StudentBuilderRoute,
  StudentEditRoute: StudentEditRoute,
  StudentScheduleRoute: StudentScheduleRoute,
  StudentStatsRoute: StudentStatsRoute,
  StudentSummaryRoute: StudentSummaryRoute,
  TrainerBuilderRoute: TrainerBuilderRoute,
  StudentIndexRoute: StudentIndexRoute,
  TrainerIndexRoute: TrainerIndexRoute,
  StudentWorkoutIdRoute: StudentWorkoutIdRoute,
  TrainerStudentIdRoute: TrainerStudentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
